name: Go
on:
  pull_request:
    paths:
      - go/**
      - .github/workflows/go.yml
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    name: Golang Code Lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          # ci is set to go1.19 to match developer setups
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.50.0
          working-directory: ./go

  test:
    name: Golang Uint Test
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: test
        working-directory: ./go
        run: make test

  coverage:
    name: Golang Code Coverage
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run coverage
        working-directory: ./go
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          files: go/coverage.txt
#          flags: go
#          fail_ci_if_error: true